delma/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from fichas.admin import admin_site
from fichas.views import FichaIndexView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^delma/', admin_site.urls),
    url(r'^delma/login/$', auth_views.login, name='account_login'),
    url(r'^fichas/', include('fichas.urls')),
    url(r'^seguridad/', include('seguridad.urls')),
    url(r'^$', FichaIndexView.as_view(), name='index'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

fichas/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

from fichas.views import FichaList, FichaDetail, FichaSearchView, download_file

app_name = 'fichas'

urlpatterns = [
    url(r'^$', FichaSearchView.as_view(), name='search'),
    url(r'^media/(?P<name>[\w\.]+)$', download_file, name='media'),
    url(r'^search/$', FichaList.as_view(), name='ficha-list'),
    url(r'^(?P<pk>[0-9]+)/$', FichaDetail.as_view(), name='ficha-detail'),

]

seguridad/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'seguridad'

urlpatterns = [
    url(r'^login/$', auth_views.login,{'template_name': 'seguridad/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout,{'template_name': 'seguridad/logout.html'}, name='logout'),
]

fichas/models.py
from django.db import models
from uuid import uuid4
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone


def path_and_rename(instance, filename):
    instance.nombre = filename
    ext = filename.split('.')[-1]
    if instance.pk:
        filename = '{}.{}'.format(instance.pk, ext)
    else:
        filename = '{}.{}'.format(uuid4().hex, ext)
    return filename


# Create your models here.
class Paciente(models.Model):
    nombre = models.CharField(max_length=64)
    apellido1 = models.CharField(max_length=32)
    apellido2 = models.CharField(max_length=32)
    direccion = models.CharField(max_length=512)
    telefono = models.CharField(max_length=32)
    correo = models.EmailField()
    dni = models.CharField(max_length=16)
    nacimiento = models.DateTimeField()
    alta = models.DateTimeField()

    def _get_nombre_completo(self):
        """Devuelve el nombre completo de la persona."""
        return '%s %s %s' % (self.nombre, self.apellido1, self.apellido2)
    nombre_completo = property(_get_nombre_completo)

    def edad(self):
        años = timezone.now().year - self.nacimiento.year

        return años


    def __str__(self):
        return self.nombre_completo


class Ficha(models.Model):

    TERAPEUTA_CHOICES = (
        ('ALB', _('ALBERTO')),
        ('DEL', _('DELFIN')),
        ('CAR', _('CAROLINA')),
    )

    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE,
                                 related_name='consultas')
    lesion = models.CharField(max_length=1024)
    cuando = models.DateTimeField()
    como = models.CharField(max_length=1024)
    mov = models.CharField(max_length=12)
    prosup = models.CharField(max_length=12)
    flex = models.CharField(max_length=12)
    ext = models.CharField(max_length=12)
    rot = models.CharField(max_length=12)
    tm = models.CharField(max_length=12)
    rte = models.CharField(max_length=24)
    emg = models.CharField(max_length=128)
    pc = models.CharField(max_length=24)
    dr = models.CharField(max_length=24)
    tratamiento_ee = models.BooleanField(default=False)
    tratamiento_ir = models.BooleanField(default=False)
    tratamiento_tm = models.BooleanField(default=False)
    tratamiento_us = models.BooleanField(default=False)
    tratamiento_l = models.BooleanField(default=False)
    tratamiento_mg = models.BooleanField(default=False)
    tratamiento_cines = models.BooleanField(default=False)
    tratamiento_synm = models.BooleanField(default=False)
    tratamiento_tc = models.BooleanField(default=False)
    tratamiento_ps = models.BooleanField(default=False)
    tratamiento_epte = models.BooleanField(default=False)
    observaciones = models.TextField()
    terapeuta = models.CharField(max_length=3, choices=TERAPEUTA_CHOICES,
                                 default='ALB')
    dolor = models.CharField(max_length=128)
    sesiones = models.TextField(max_length=1024)

    def __str__(self):
        return self.paciente.nombre_completo


class Adjunto(models.Model):
    ficha = models.ForeignKey(Ficha, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=128)
    fichero = models.FileField(upload_to=path_and_rename)


class Abono(models.Model):
    cliente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    periodo_inicio = models.DateField()
    periodo_fin = models.DateField()
    importe = models.DecimalField(max_digits=7, decimal_places=2,
                                  null=True, blank=True, default=0)
    pagado = models.BooleanField(default=False)

seguridad/models.py
from django.db import models

# Create your models here.

fichas/views.py
from django.shortcuts import render
from django.conf import settings
import os, mimetypes

# Create your views here.
import logging
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, TemplateView
from django.db.models import Q
from fichas.models import Ficha
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required


@login_required(login_url='/seguridad/login/')
def download_file(request, name):
    mimetype = mimetypes.guess_type(os.path.join(settings.MEDIA_ROOT, name))
    with open(os.path.join(settings.MEDIA_ROOT, name), 'rb') as f:
        response = HttpResponse(f, content_type=mimetype)
        response['Content-Disposition'] = "attachment; filename=%s" % \
                                          (name)
        return response


class FichaList(LoginRequiredMixin, ListView):
    model = Ficha
    login_url = '/seguridad/login/'

    def get_queryset(self):
        qs = super(FichaList, self).get_queryset()
        nombre = self.request.GET.get('nombre')
        if nombre:
            logging.error("AQUIIIIII")
            # return qs.filter(paciente__apellido1__icontains=nombre)
            return qs.filter(Q(paciente__apellido1__icontains=nombre) |
                             Q(paciente__nombre__icontains=nombre))
        return qs


class FichaDetail(LoginRequiredMixin, DetailView):
    login_url = '/seguridad/login/'
    model = Ficha


class FichaIndexView(LoginRequiredMixin, TemplateView):
    login_url = '/seguridad/login/'
    template_name = 'fichas/index.html'


class FichaSearchView(LoginRequiredMixin, TemplateView):
    login_url = '/seguridad/login/'
    template_name = 'fichas/search.html'

seguridad/views.py
from django.shortcuts import render

# Create your views here.

fichas/templates/fichas/base.html
{% load i18n admin_static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "fichas/css/siimple.css" %}{% endblock %}" />
<link rel="stylesheet" type="text/css" href="{% static "fichas/css/style.css" %}" />
{% block extrastyle %}{% endblock %}
{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
<!-- Place this tag in your head or just before your close body tag. -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
</head>
{% load i18n %}
<body>
<!-- Place this tag in your head or just before your close body tag. -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
  <div class="navbar">
    <a class="navbar-logo" href="{% url 'index' %}">Delma</a>
    {% if user.is_authenticated %}
    <div class="navbar-user">Bienvenido {% firstof user.get_short_name user.get_username %}</div>
        {% if user.is_active and user.is_staff %}
        <a class="navbar-link" href="{% url 'account_login' %}">Administrar</a>
        {% endif %}
        {% if user.has_usable_password %}
        <a class="navbar-link" href="{% url 'admin:password_change' %}">Cambiar contraseña</a> 
        {% endif %}
    <a class="navbar-link" href="{% url 'seguridad:logout' %}">Cerrar sesión</a>
    {% else %}
    <a class="navbar-link" href="{% url 'seguridad:login' %}">Inciar sesión</a>
    {% endif %}
  </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    {{ breadcrumbs }}
    {% endblock %}
    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}
</div>
    <!-- Content -->
        {% block content %}
        {{ content }}
        {% endblock %}
    <!-- END Content -->

    {% block footer %}
    <div class="foot">
       <a class="foot-logo" href="{% url 'index' %}">Delma</a>
           Aplicación hecha con <span class="heart"></span> por
       <a href="https://github.com/reciproco/delma">Javier Segura</a>
       usando <a href="https://www.djangoproject.com/">Django</a>
    </div>
    {% endblock %}
<!-- END Container -->
</body>
</html>

fichas/templates/fichas/ficha_detail.html
{% extends "fichas/base.html" %}
{% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'index' %}">Inicio</a> &rsaquo; <a href="{% url 'fichas:search' %}">Buscar</a> &rsaquo; <a href="{% url 'fichas:ficha-list' %}">Lista de fichas</a>
    &rsaquo; <a href="{% url 'fichas:ficha-detail' object.id %}">{{object.paciente}} ({{ object.cuando }})</a>
    </div>
{% endblock %}
{% block content %}

    <div id="card">
      <div class="grid grid-fluid">
        <div class="row">
          <div class="col-6" class="card-paciente"><strong>PACIENTE: </strong>{{ object.paciente }}</div>
          <div class="col-3"></div>
          <div class="col-3"><strong>EDAD: </strong>{{ object.paciente.edad }}</div>
        </div>
        <div class="row">
          <div class="col-12" class="card-paciente"><strong>LESIÓN: </strong>{{ object.lesion }}</div>
        </div>
        <div class="row">
          <div class="col-4" class="card-paciente"><strong>CUÁNDO: </strong>{{ object.cuando }}</div>
          <div class="col-8"><strong>CÓMO: </strong>{{ object.como }}</div>
        </div>
        <div class="row">
          <div class="col-2" class="card-paciente"><strong>MOV: </strong>{{ object.mov }}</div>
          <div class="col-2" class="card-paciente"><strong>PRO/SUP: </strong>{{ object.prosup }}</div>
          <div class="col-2" class="card-paciente"><strong>FLEX: </strong>{{ object.flex }}</div>
          <div class="col-2" class="card-paciente"><strong>EXT: </strong>{{ object.ext }}</div>
          <div class="col-2" class="card-paciente"><strong>ROT: </strong>{{ object.rot }}</div>
          <div class="col-2" class="card-paciente"><strong>TM: </strong>{{ object.tm }}</div>
        </div>
        <div class="col-12">
         <strong>TRATAMIENTO:</strong>
         {% if object.tratamiento_ee %}
         <label style="color:green;">EE</label>
         {% else %}
         <label style="color:#C0C0C0;">EE</label>
         {% endif %}
         {% if object.tratamiento_ir %}
         <label style="color:green;">IR</label>
         {% else %}
         <label style="color:#C0C0C0;">IR</label>
         {% endif %}
         {% if object.tratamiento_tm %}
         <label style="color:green;">TM</label>
         {% else %}
         <label style="color:#C0C0C0;">TM</label>
         {% endif %}
         {% if object.tratamiento_us %}
         <label style="color:green;">US</label>
         {% else %}
         <label style="color:#C0C0C0;">US</label>
         {% endif %}
         {% if object.tratamiento_l %}
         <label style="color:green;">L</label>
         {% else %}
         <label style="color:#C0C0C0;">L</label>
         {% endif %}
         {% if object.tratamiento_mg %}
         <label style="color:green;">MG</label>
         {% else %}
         <label style="color:#C0C0C0;">MG</label>
         {% endif %}
         {% if object.tratamiento_cines %}
         <label style="color:green;">CINES</label>
         {% else %}
         <label style="color:#C0C0C0;">CINES</label>
         {% endif %}
         {% if object.tratamiento_synm %}
         <label style="color:green;">SYNM</label>
         {% else %}
         <label style="color:#C0C0C0;">SYNM</label>
         {% endif %}
         {% if object.tratamiento_tc %}
         <label style="color:green;">TC</label>
         {% else %}
         <label style="color:#C0C0C0;">TC</label>
         {% endif %}
         {% if object.tratamiento_ps %}
         <label style="color:green;">PS</label>
         {% else %}
         <label style="color:#C0C0C0;">PS</label>
         {% endif %}
         {% if object.tratamiento_epte %}
         <label style="color:green;">EPTE</label>
         {% else %}
         <label style="color:#C0C0C0;">EPTE</label>
         {% endif %}
        </div>
       </div>
       <div class="row">
         <div class="col-4" class="card-paciente"><strong>TERAPEUTA: </strong>{{ object.terapeuta }}</div>
         <div class="col-4" class="card-paciente"><strong>RTE: </strong>{{ object.rte }}</div>
         <div class="col-4" class="card-paciente"><strong>EMG: </strong>{{ object.emg }}</div>
       </div>
       <div class="row">
         <div class="col-2" class="card-paciente"><strong>PC: </strong>{{ object.pc }}</div>
         <div class="col-3" class="card-paciente"><strong>DR: </strong>{{ object.dr }}</div>
         <div class="col-7" class="card-paciente"><strong>DOLOR: </strong>{{ object.dolor }}</div>
       </div>
        <div class="row">
          <div class="col-12" class="card-paciente"><strong>OBSERVACIONES: </strong>{{ object.observaciones }}</div>
        </div>
        <div class="row">
          <div class="col-12" class="card-paciente"><strong>SESIONES: </strong>{{ object.sesiones }}</div>
        </div>
        <div class="row">
          <div class="col-12">
            <strong>FICHEROS:</strong>
            {% for i in object.adjunto_set.all %}
                <a href="{{ i.fichero.url }}">"{{i.nombre}}"</a>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
{% endblock %}

fichas/templates/fichas/ficha_list.html
{% extends "fichas/base.html" %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'index' %}">Inicio</a> &rsaquo; <a href="{% url 'fichas:search' %}">Buscar</a> &rsaquo; <a href="{% url 'fichas:ficha-list' %}">Lista de fichas</a>
    </div>
{% endblock %}
{% block content %}
<div id="main-content">
    <h2>Listado</h2>
        <table class="table table-striped">
          <thead>
            <tr>
              <td>Ficha</td><td>Fecha</td>
            </tr>
          </thead>
        {% for ficha in object_list %}
        <tr>
            <td><a href="{% url 'fichas:ficha-detail' pk=ficha.id %}">{{ ficha.paciente }}</a></td>
            <td>{{ ficha.cuando }}</td>
        </tr>
        {% endfor %}
        </table>
</div>
{% endblock %}

fichas/templates/fichas/index.html
{% extends "fichas/base.html" %}

{% block content %}
<div class="cover" align="center">
<div class="cover-title">Delma</div>
<div class="cover-description">Aplicación para gestión de fichas de pacientes.</div>
<a class="btn-outline cover-btn" href="{% url 'fichas:search' %}">Buscar fichas</a>
<a class="btn-outline cover-btn" href="{% url 'account_login' %}">Administrar</a>
<br>
<span class="text-small">Para comenzar pulse en cualquiera de las opciones</span>
</div>
<div class="gh-btns" align="center">
<h4>¿Quieres ayudar?</h4>
<p>Puedes ayudar con el desarrollo de la aplicación enviando bugs y pull request</p>
<!-- Place this tag where you want the button to render. -->
<a aria-label="Star reciproco/delma on GitHub" data-count-aria-label="# stargazers on GitHub" data-count-api="/repos/reciproco/delma#stargazers_count" data-count-href="/reciproco/delma/stargazers" href="https://github.com/reciproco/delma" class="github-button">Star</a>
<!-- Place this tag where you want the button to render. -->
<a aria-label="Fork reciproco/delma on GitHub" data-count-aria-label="# forks on GitHub" data-count-api="/repos/reciproco/delma#forks_count" data-count-href="/reciproco/delma/network" href="https://github.com/reciproco/delma/fork" class="github-button">Fork</a>
</div>
{% endblock %}

fichas/templates/fichas/search.html
{% extends "fichas/base.html" %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'index' %}">Inicio</a> &rsaquo; <a href="{% url 'fichas:search' %}">Buscar</a>
    </div>
{% endblock %}
{% block content %}
<div id="main-content">

  <form id="searchform" action="{% url 'fichas:ficha-list' %}" method="get" accept-charset="utf-8">
        <input class="form-input" id="searchbox" name="nombre" type="text" placeholder="Busqueda de pacientes">
        <input class="form-input" type="submit" value="Buscar">
  </form>
</div>

{% endblock %}

seguridad/templates/seguridad/login.html
{% extends "fichas/base.html" %}
{% load seguridad_extras %}

{% block content %}
<div id="main-content">
  {% if form.errors %}
  <div class="alert alert-error">Usuario o contraseña incorrectos. Inténtelo de nuevo</div>
  {% endif %}

  {% if next %}
      {% if user.is_authenticated %}
      <p class=" alert alert-error">Your account doesn't have access to this page. To proceed,
      please login with an account that has access.</p>
      {% else %}
      <p class="alert alert-error">Por favor inicie sesión para acceder a esta página</p>
      {% endif %}
  {% endif %}

  <form method="post" action="{% url 'seguridad:login' %}">
  {% csrf_token %}
  <table>
  <tr>
      <td><h5>{{ form.username.label_tag }}</h5></td>
      <td>{{ form.username|addcss:'form-input' }}</td>
  </tr>
  <tr>
      <td><h5>{{ form.password.label_tag }}</h5></td>
      <td>{{ form.password|addcss:'form-input' }}</td>
  </tr>
  </table>

  <input class="form-input" type="submit" value="Entrar" />
  <input type="hidden" name="next" value="{{ next }}" />
  </form>
</div>

{% endblock %}

seguridad/templates/seguridad/logout.html
{% extends "fichas/base.html" %}
{% load i18n %}

{% block breadcrumbs %}<div class="breadcrumbs"><a href="{% url 'index' %}">{% trans 'Home' %}</a></div>{% endblock %}

{% block content %}
<div id="main-content">
  <p>{% trans "Gracias por utilizar la aplicación." %}</p>

  <p><a href="{% url 'seguridad:login' %}">{% trans 'Identificarse de nuevo' %}</a></p>
</div>
{% endblock %}